University.Web/Controllers/CourseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using University.Services.Dto;
using University.Services.Interfaces;
using University.Web.Models.ViewModels.CoursesViewModels;

namespace University.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IService<CourseDto> _service;

        public CourseController(IService<CourseDto> service, IMapper mapper)
        {
            _mapper = mapper;
            _service = service;
        }

        public async Task<ActionResult> Index()
        {
            var model = await PrepareIndexViewModelAsync();

            return IsModelEmpty(model) ? RedirectToAction("Create") : View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            var viewModel = await PrepareViewModelAsync<CourseDetailsViewModel>(id);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View(new CourseCreateViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> Create(CourseCreateViewModel modelFromView)
        {
            if (!ModelState.IsValid)
                return View();

            var modelDto = _mapper.Map<CourseDto>(modelFromView);
            await _service.CreateAsync(modelDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Edit(int id)
        {
            var viewModel = await PrepareViewModelAsync<CourseEditViewModel>(id);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CourseEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var modelDto = _mapper.Map<CourseDto>(model);
            await _service.EditAsync(modelDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Delete(int id)
        {
            var viewModel = await PrepareViewModelAsync<CourseDeleteViewModel>(id);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(CourseDeleteViewModel model)
        {
            var modelDto = _mapper.Map<CourseDto>(model);
            await _service.DeleteAsync(modelDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> VerifyNameForCreating(string name)
        {
            if (await _service.VerifyNameAsync(name))
                return Json(true);

            return Json($"A course named {name} already exists.");
        }

        public async Task<ActionResult> VerifyNameForEditing(string name, int id)
        {
            if (await _service.VerifyNameAsync(name, id))
                return Json(true);

            return Json($"A course named {name} already exists.");
        }

        private static bool IsModelEmpty(IEnumerable<CourseIndexViewModel> model)
        {
            return !model.Any();
        }

        private async Task<IEnumerable<CourseIndexViewModel>> PrepareIndexViewModelAsync()
        {
            var listOfModelsDto = await _service.GetListAsync();

            return _mapper.Map<IEnumerable<CourseIndexViewModel>>(listOfModelsDto);
        }

        private async Task<TViewModel> PrepareViewModelAsync<TViewModel>(int id)
        {
            var modelDto = await _service.GetByIdAsync(id);

            return _mapper.Map<TViewModel>(modelDto);
        }
    }
}

University.Web/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using University.Services.Dto;
using University.Services.Interfaces;
using University.Web.Models.ViewModels.GroupsViewModels;

namespace University.Web.Controllers
{
    public class GroupController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IService<GroupDto> _service;

        public GroupController(IMapper mapper, IService<GroupDto> service)
        {
            _mapper = mapper;
            _service = service;
        }

        public async Task<ActionResult> Index(int courseId)
        {
            var model = await PrepareIndexViewModelAsync(courseId);

            return ModelIsEmpty(model) ? RedirectToAction("Create", new {courseId}) : View(model);
        }

        private static bool ModelIsEmpty(IEnumerable<GroupIndexViewModel> model)
        {
            return !model.Any();
        }

        public async Task<ActionResult> Details(int id)
        {
            var modelView = await PrepareModelViewAsync<GroupDetailsViewModel>(id);

            return View(modelView);
        }

        public ActionResult Create(int courseId)
        {
            var model = new GroupCreateViewModel {CourseId = courseId};

            return View(model);
        }

        public async Task<ActionResult> IfGroupExist(int id)
        {
            var courseDto = await _service.GetByIdAsync(id);
            var viewModel = _mapper.Map<GroupCreateViewModel>(courseDto);
            ModelState.AddModelError("Name", "There is the same name among the groups");

            return View("~/Views/Group/Create.cshtml", viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Create(GroupCreateViewModel groupView)
        {
            if (!ModelState.IsValid)
                return View();

            var group = _mapper.Map<GroupDto>(groupView);
            await _service.CreateAsync(group);

            return RedirectToAction(nameof(Index), new {courseId = groupView.CourseId});
        }

        public async Task<ActionResult> Edit(int id)
        {
            var modelView = await PrepareModelViewAsync<GroupEditViewModel>(id);

            return View(modelView);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(GroupEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var modelDto = _mapper.Map<GroupDto>(model);
            await _service.EditAsync(modelDto);

            return RedirectToAction(nameof(Index), new {courseId = model.CourseId});
        }

        public async Task<ActionResult> Delete(int id)
        {
            var model = await PrepareModelViewAsync<GroupDeleteViewModel>(id);

            if (model.NumberStudents != 0)
                ModelState.AddModelError("NumberStudents", "You can't delete this group if there are students");

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(GroupDeleteViewModel model)
        {
            var modelDto = _mapper.Map<GroupDto>(model);
            await _service.DeleteAsync(modelDto);

            return RedirectToAction(nameof(Index), new {courseId = model.CourseId});
        }

        public async Task<ActionResult> VerifyNameForCreating(string name)
        {
            if (await _service.VerifyNameAsync(name))
                return Json(true);

            return Json($"A group named {name} already exists.");
        }

        public async Task<ActionResult> VerifyNameForEditing(string name, int id)
        {
            if (await _service.VerifyNameAsync(name, id))
                return Json(true);

            return Json($"A group named {name} already exists.");
        }

        private async Task<IEnumerable<GroupIndexViewModel>> PrepareIndexViewModelAsync(int courseId)
        {
            var listOfModelsDto = await _service.GetListAsync(courseId);

            return _mapper.Map<IEnumerable<GroupIndexViewModel>>(listOfModelsDto);
        }

        private async Task<TViewModel> PrepareModelViewAsync<TViewModel>(int id)
        {
            var modelDto = await _service.GetByIdAsync(id);

            return _mapper.Map<TViewModel>(modelDto);
        }
    }
}

University.Web/Views/Group/Create.cshtml
@model University.Web.Models.ViewModels.GroupsViewModels.GroupCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create new group</h1>

<div>
    <a asp-action="Index" asp-controller="Course">Back to list of courses</a>
</div>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="CourseId" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-courseId="@Model.CourseId">Back to list of groups</a>
</div>

University.Web/Views/Group/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@model University.Web.Models.ViewModels.GroupsViewModels.GroupDeleteViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete group</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberStudents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberStudents)
        </dd>
        <dt class="col-12">
            <span asp-validation-for="NumberStudents" class="text-danger"></span>
        </dt>
    </dl>

    <form asp-action="Delete" method="post">

        <input asp-for="Id" value="@Model.Id" type="hidden"/>
        <input asp-for="CourseId" value="@Model.CourseId" type="hidden"/>
        <input asp-for="NumberStudents" value="@Model.NumberStudents" type="hidden"/>
        <input asp-for="CourseName" value="@Model.CourseName" type="hidden"/>
        <input asp-for="Name" value="@Model.Name" type="hidden"/>

        @if (Model.NumberStudents != 0)
        {
            <input type="submit" value="Delete" class="btn btn-danger" disabled="disabled"/>
        }
        else
        {
            <input type="submit" value="Delete" class="btn btn-danger"/>
        }
        |
        <a asp-action="Index" asp-controller="Group" asp-route-courseId="@Model.CourseId">Back to list of the groups</a>
    </form>
</div>

University.Web/Views/Group/Details.cshtml
@model University.Web.Models.ViewModels.GroupsViewModels.GroupDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details of the group</h1>

<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberStudents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberStudents)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-route-courseId="@Model.CourseId">Back to List</a>
</div>

University.Web/Views/Group/Edit.cshtml
@model University.Web.Models.ViewModels.GroupsViewModels.GroupEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Group" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="CourseId" class="form-control"/>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CourseName" class="control-label"></label>
                <select asp-for="CourseName" class="form-control">
                    @foreach (var item in Model.ListOfCoursesNames)
                    {
                        <option>@item</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-courseId="@Model.CourseId">Back to list of the groups</a>
</div>

University.Web/Views/Group/Index.cshtml
@model IEnumerable<University.Web.Models.ViewModels.GroupsViewModels.GroupIndexViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>@Model.First().CourseName</h1>

<div>
    <a asp-action="Index" asp-controller="Course">Back to list of courses</a>
</div>

<p>
    <a asp-action="Create" asp-route-courseId="@Model.First().CourseId">Create new group</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.First().NumberStudents)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.NumberStudents == 0)
                {
                    <a asp-controller="Student" asp-action="Create" asp-route-groupId="@item.Id" asp-route-courseId="@item.CourseId">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                }
                else
                {
                    <a asp-controller="Student" asp-action="Index" asp-route-groupId="@item.Id">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberStudents)
            </td>
            <td>
                <p>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </p>
            </td>
        </tr>
    }
    </tbody>
</table>